# Workflow File

[resources]
cluster_type = "SLURMCluster" # Could be any cluster type supported by Job Queue, but obviously must match the Workload Manager used by the HPC Cluster.
n_workers = 10

[resources.worker]
# per worker params (any of those supported by that cluster type in Jobqueue)
cores = 8
processes = 4
memory = "16GB"
project = "MyProject"
Walltime = "01:00:00"
queue = "normal"

[job1]
[job1.tasks]
task1 = '''echo 'job1-task1' &&
touch 'job1-task1' &&
sleep 5
'''
task2 = '''echo 'job1-task2' &&
touch 'job1-task2' &&
sleep 5
'''

[job2]
depends = ["job1"]
[job2.tasks]
task1 = '''echo 'job2-task1' &&
touch 'job2-task1' &&
sleep 5
'''
task2 = '''echo 'job2-task2' &&
touch 'job2-task2' &&
sleep 5
'''

